import type { StartupEvent } from "./types";

/** Fictional fixtures, deliberately unsorted. Never treat these as real listings. */
export const mockEvents: readonly StartupEvent[] = [
  {
    id: "mock-product-003",
    title: "Behind the product: zero to one",
    organizer: "Product People NYC",
    startsAt: "2026-09-03T18:00:00-04:00",
    endsAt: "2026-09-03T20:00:00-04:00",
    timeZone: "America/New_York",
    venue: "The Workshop",
    neighborhood: "Flatiron",
    borough: "Manhattan",
    categories: ["Product", "SaaS"],
    priceUsd: 15,
    source: "Meetup",
    registrationStatus: "open",
    isNew: false,
    founderScore: 78,
    investorScore: 42,
    networkingScore: 86,
    recommendation:
      "Small breakout groups pair early-stage product leads with founders. A strong room for swapping practical lessons and finding future collaborators.",
    potentialDownside: "More operator-focused than investor-focused.",
  },
  {
    id: "mock-ai-001",
    title: "AI builders & founders: after hours",
    organizer: "Build Club NYC",
    startsAt: "2026-09-01T18:30:00-04:00",
    endsAt: "2026-09-01T21:00:00-04:00",
    timeZone: "America/New_York",
    venue: "The Mercer Loft",
    neighborhood: "SoHo",
    borough: "Manhattan",
    categories: ["AI", "Founder"],
    priceUsd: 0,
    source: "Luma",
    registrationStatus: "almost-full",
    isNew: true,
    founderScore: 96,
    investorScore: 72,
    networkingScore: 94,
    recommendation:
      "A founder-heavy room with live demos and plenty of unstructured time. Ideal for meeting people actively building in AI, beyond the usual panel circuit.",
    potentialDownside:
      "Technical conversations may be less useful if you’re looking for general career advice.",
  },
  {
    id: "mock-pitch-005",
    title: "First checks: founder pitch night",
    organizer: "First Check Collective",
    startsAt: "2026-09-04T18:00:00-04:00",
    endsAt: "2026-09-04T20:30:00-04:00",
    timeZone: "America/New_York",
    venue: "Broadway Exchange",
    neighborhood: "NoMad",
    borough: "Manhattan",
    categories: ["Pitch", "VC", "Founder"],
    priceUsd: 30,
    source: "Eventbrite",
    registrationStatus: "waitlist",
    isNew: false,
    founderScore: 85,
    investorScore: 88,
    networkingScore: 80,
    recommendation:
      "Early-stage pitches followed by an investor Q&A and reception. Useful for learning how investors think and making a few focused introductions.",
    potentialDownside:
      "Most of the evening is seated; networking time is limited and entry is waitlisted.",
  },
  {
    id: "mock-vc-002",
    title: "Coffee, capital & candid conversations",
    organizer: "Seed Circle",
    startsAt: "2026-09-02T08:30:00-04:00",
    endsAt: "2026-09-02T10:00:00-04:00",
    timeZone: "America/New_York",
    venue: "Union House",
    neighborhood: "Union Square",
    borough: "Manhattan",
    categories: ["Founder", "VC"],
    priceUsd: 20,
    source: "Luma",
    registrationStatus: "almost-full",
    isNew: true,
    founderScore: 91,
    investorScore: 95,
    networkingScore: 91,
    recommendation:
      "An intimate breakfast format gives founders space for actual conversations with seed investors. Especially relevant if you’re preparing your first raise.",
    potentialDownside:
      "An early start, with a stronger fundraising focus than product or hiring.",
  },
  {
    id: "mock-saas-004",
    title: "Bootstrapped in Brooklyn",
    organizer: "Independent Founders Guild",
    startsAt: "2026-09-05T10:00:00-04:00",
    endsAt: "2026-09-05T12:00:00-04:00",
    timeZone: "America/New_York",
    venue: "Bridge Street Studio",
    neighborhood: "DUMBO",
    borough: "Brooklyn",
    categories: ["Founder", "SaaS"],
    priceUsd: 0,
    source: "Organizer website",
    registrationStatus: "open",
    isNew: true,
    founderScore: 93,
    investorScore: 28,
    networkingScore: 84,
    recommendation:
      "Peer-led conversations about first customers, pricing, and sustainable growth. A good fit for finding founder friends with similar day-to-day challenges.",
  },
  {
    id: "mock-ai-006",
    title: "Shipping AI: a Sunday demo session",
    organizer: "Weekend Builders",
    startsAt: "2026-09-06T14:00:00-04:00",
    endsAt: "2026-09-06T17:00:00-04:00",
    timeZone: "America/New_York",
    venue: "Northside Workroom",
    neighborhood: "Williamsburg",
    borough: "Brooklyn",
    categories: ["AI", "Product"],
    priceUsd: 0,
    source: "Meetup",
    registrationStatus: "open",
    isNew: false,
    founderScore: 70,
    investorScore: 20,
    networkingScore: 76,
    recommendation:
      "A hands-on crowd sharing work in progress. Worth considering for project feedback, potential collaborators, and a closer look at what people are shipping.",
    potentialDownside:
      "A mixed experience level and little direct access to investors.",
  },
];
